### ISSUE TITLE
Add pipeline configs to dag default_args in rainbow_dags

### ISSUE THREAD

**Issue by aviem-naturalint** [Natural-Intelligence/liminal#13]
Add all `pipeline` config fields (Which are not themselves objects, like tasks is) to the DAG's default_args, this way the user can enter any DAG configuration there.
This allows the users to configure any airflow configuration using the `pipeline` configuration.
Document relevant configurations in our documentation.

**Comment by odedros** [comment]
removed the flat field restriction from the code in PR
default_args is applied to each operator (or any other object) which uses the @apply_defaults annotation which is implemented [here](https://github.com/apache/airflow/blob/6c273466d598d7bcfb7c21feafcccb07cc4230fb/airflow/utils/decorators.py#L30)
since each object can (does) have different set of fields there's no close set of values we can validate.
